
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SET_CATEGORIES_ID = 'APP/SET_CATEGORIES_ID'
export const SET_SERVICES_ID = 'APP/SET_SERVICES_ID'
export const SET_SERVICE_ID = 'APP/SET_SERVICE_ID'
export const SHOW_POPUP = 'APP/SHOW_POPUP'
export const HIDE_POPUP = 'APP/HIDE_POPUP'

export const FETCH_SUPERCATEGORIES = 'FETCH_SUPERCATEGORIES'

export const FETCH_СATEGORIES = 'FETCH_СATEGORIES'
export const GET_СATEGORIES = 'GET_СATEGORIES'

export const FETCH_SERVICES = 'FETCH_SERVICES'

export const FETCH_SERVICE = 'FETCH_SERVICE'

export const GET_SERVICES = 'GET_SERVICES'





