
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const FETCH_SUPERCATEGORIES = 'FETCH_SUPERCATEGORIES'
export const FETCH_СATEGORIES = 'FETCH_СATEGORIES'
export const FETCH_SERVICES = 'FETCH_SERVICES'
export const FETCH_SERVICE = 'FETCH_SERVICE'

export const SET_CATEGORIES_LINK = 'SET_CATEGORIES_LINK'
export const SET_SERVICES_LINK = 'SET_SERVICES_LINK'
export const SET_SERVICE_LINK = 'SET_SERVICE_LINK'

