
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const FETCH_SUPERCATEGORIES = 'FETCH/FETCH_SUPERCATEGORIES'
export const FETCH_SERVICE = 'FETCH/FETCH_SERVICE'
