# Generated by Django 3.1.2 on 2020-10-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201014_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='supercategory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.supercategory'),
        ),
    ]
