# Generated by Django 3.1.2 on 2020-10-28 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201014_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['supercategory_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='supercategory',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='category',
            name='svg_icon',
            field=models.FileField(blank=True, null=True, upload_to='svg/', validators=[django.core.validators.FileExtensionValidator('svg')], verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='supercategory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.supercategory', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя подкатегории'),
        ),
        migrations.AlterField(
            model_name='supercategory',
            name='supercategory_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя раздела'),
        ),
    ]
